name: TreeChopChopper
version: '${project.version}'
main: org.s1queence.TreeChopChopper
api-version: '1.21'
depend: [S1queenceLib]
commands:
  treechopchopper:
    usage: /tcc reload
    permission: tcc.perms.reload
    aliases:
      - tcc